name: chrisyauckphotography
favicon: null
layout_spectrum: 0.98532
typography_spectrum: 0.17266108701005578
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5dadd'
    - '#28292b'
    - '#60686b'
    - '#85979b'
    - '#cb677f'
  brandStrength: 0.6875
  lightness: 0.36777533614076674
  saturation: 0
  rhythmicContrast: 0.9496160226408392
purpose: []
